const express = require('express');

const router = express.Router();

const DataEntry = require('../models/DataEntry');

const auth = require('../middleware/auth');



// @route   POST /api/data

// @desc    Add new entry with Reflection Trigger

router.post('/', auth, async (req, res) => {

    try {

        const { type, date, amount, payer, note, consumptionData, pricePerEgg, time } = req.body;



        // 1. Save the Primary Transaction

        const mainEntry = new DataEntry({

            type, date, amount: Number(amount), payer, consumptionData,

            pricePerEgg: Number(pricePerEgg) || 6, note, time

        });

        const saved = await mainEntry.save();



        // 2. REFLECTION TRIGGER: If Vivek ('v') pays for Eggs or Petrol

        if ((type === 'egg_pay' || type === 'bike_pay') && payer === 'v') {

            const reflection = new DataEntry({

                type: 'expense',

                date: date,

                time: time || "10:00 AM",

                amount: Number(amount),

                note: type === 'egg_pay' ? '🥚 Reflected: Egg Purchase' : '⛽ Reflected: Petrol Filling',

                isAutoGenerated: true

            });

            await reflection.save();

        }



        res.json(saved);

    } catch (err) {

        console.error(err.message);

        res.status(500).send('Server Error');

    }

});



// @route   GET /api/data

router.get('/', async (req, res) => {

    try {

        const data = await DataEntry.find().sort({ date: -1 });

        res.json(data);

    } catch (err) { res.status(500).send('Server Error'); }

});



// @route   DELETE /api/data/:id

router.delete('/:id', auth, async (req, res) => {

    try {

        await DataEntry.findByIdAndDelete(req.params.id);

        res.json({ msg: 'Entry removed' });

    } catch (err) { res.status(500).send('Server Error'); }

});



module.exports = router;


