const mongoose = require('mongoose');

const DataEntrySchema = new mongoose.Schema({
    type: { type: String, required: true }, // egg_log, egg_pay, bike_pay, expense
    date: { type: Date, required: true },
    amount: { type: Number },
    payer: { type: String },
    consumptionData: { type: String }, // "1v ; 2h"
    pricePerEgg: { type: Number, default: 6 },
    note: { type: String },
    time: { type: String },
    isAutoGenerated: { type: Boolean, default: false }
});

module.exports = mongoose.model('DataEntry', DataEntrySchema);